### ISSUE TITLE
1.9 TODO

### ISSUE THREAD

**Issue by TehNut** [TeamAmeriFrance/Guide-API#26]
## Immediate tasks
- [x] Move to `IForgeRegistry`. This allows persistence between worlds and servers.
- [x] Make the API look like an API. It currently looks like a big mish-mash of classes.
- [x] Fix issues with some models not rendering correctly in the GUI. Most work, but others are broken (eg: Beacon)
- [x] Move entries from a `List<EntryAbstract>` to a `Map<ResourceLocation, EntryAbstract>`. This will make entry lookups for `IGuideLinked` much cleaner.
- [ ] Clean up visuals a bit. They're not horrible, but they could definitely be better.
- [ ] Clean up the JSON system. It's currently a _huge_ chore to write JSON books.
## Down the road tasks
- [ ] In-game guide editing (For JSON system)
- [ ] HTML exporter
## Stretch features
- [ ] Support for more guide formats. (Markdown, HTML, etc)
